# Generated by Django 5.1.6 on 2025-02-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='grade',
            new_name='rating',
        ),
    ]
