# Generated by Django 5.1.6 on 2025-02-08 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_grade_movies_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='sketch',
            new_name='inq',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='num_evaluate',
            new_name='num_judge',
        ),
    ]
